### ISSUE TITLE
Registry degrades and reports corruption

### ISSUE THREAD

**Issue by Henkis** [docker/docker-registry#540]
We are using a privately hosted registry on amazon which seems to degrade after we have pulled larger images (1GB+) a few times from it, it finely stop responding. A restart of the registry container seems to fix the problem for a while:

```
df29cb2b16e8: Download complete
8673c2be5440: Download complete
efb1cc4f166f: Error downloading dependent layers
2014/08/26 23:09:14 Error pulling image (97a9cc4076fd69d8a35be028a74f0e00b8066555) from 256.31.14.183/server, flate: corrupt input before offset 13576289
```

And again:

```
Pulling repository 256.31.14.183/server
a44fa854766a: Error pulling image (97a9cc4076fd69d8a35be028a74f0e00b8066555) from 256.31.14.183/adserver, archive/tar: invalid tar header 1/, archive/tar: invalid tar header
5e66087f3ffe: Error downloading dependent layers
2014/08/27 06:03:14 Error pulling image (97a9cc4076fd69d8a35be028a74f0e00b8066555) from 256.31.14.183/server, archive/tar: invalid tar header
```

We often see these messages in the log but not always:

```
<Greenlet at 0x7f8bbb7269b0: <bound method ParallelKey._fetch_part of <docker_registry.core.boto.ParallelKey object at 0x7f8bbb2be550>>('/tmp/tmpPPltfO', 1, 13495293, 26990585)> failed with timeout
```

We currently use the latest registry (registry 0.8.0 cd3581c06bdc) but have hade the same problems earlier.

Registry config:

Dockerfile:

```
FROM registry
ADD ./config.yml /docker-registry/config/config.yml
```

config.yml:

```
common:
    loglevel: info
    secret_key: <OURLITTLESECRET>


# This is the default configuration when no flavor is specified
dev:
    storage: local
    storage_path: /tmp/registry
    loglevel: debug

# To specify another flavor, set the environment variable SETTINGS_FLAVOR
# $ export SETTINGS_FLAVOR=prod
prod:
    storage: s3
    storage_path: /prod
    loglevel: debug
    # Amazon S3 Storage Configuration
    s3_access_key: <OURLITTLESECRET>
    s3_secret_key: <OURLITTLESECRET>
    s3_bucket: arkivdigital-docker-registry
    boto_bucket: ourrepo-registry
    # Enabling LRU cache for small files. This speeds up read/write on small files
    # when using a remote storage backend (like S3).
    cache:
        host: docker-registryblabla.cache.amazonaws.com
        port: 6379
        db: 0
    cache_lru:
        host: docker-registryblabla.cache.amazonaws.com
        port: 6379
        db: 0

    standalone: true
    disable_token_auth: true

# This flavor is automatically used by unit tests
test:
    storage: local
    storage_path: /tmp/test
```

**Comment by dsw88** [comment]
We've got this issue too on our registries. We're running them inside an AWS VPC. We're running one registry container per host, with 6 instance currently. Those instances are fronted by an elastic load balancer whose timeout it set to 5 mins. We're using S3 as a storage backend.

After finding this thread, we set the registry with the -e STORAGE_REDIRECT=true option to delegate image downloads directly to S3. That has helped tremendously with the myriad of errors we were getting such as EOF.

However, we're still getting EOF errors on some registry calls that aren't actual image layer retrievals. For example, I saw an EOF error on a /ancestry call. I don't see any errors in the Docker Registry logs when these types of issues happen so I'm sort of at a loss.

These errors seem to happen when we have a heavier load on the registries such as 5-10 images pulling from the registries from the same time. However, that doesn't seem like a heavy load especially with storage redirect and 6 instances of the registry behind a load balancer.

**Comment by dmp42** [comment]
@all we recently removed ParallelKey fetch from S3 from the registry - it was triggering timeouts for large objects, and cluttering disk space with orphaned temporary files.
It's hard to tell if any of the side-effects you experienced here are linked to it or not, but that removal can sure only help.

**Comment by dsw88** [comment]
Hmm that might help, is there any documentation on how to disable that feature on our registries? I'm using the container so I've usually just had environment variables that map to what's in the YAML config file, but I don't see the option you mentioned in that YAML config file schema.

**Comment by dmp42** [comment]
It's code removal (#961).
You can test by using the latest master.

**Comment by dsw88** [comment]
Ok I'm trying the fix out now, I'll have to wait a few days to validate whether our percentage of deploy failures when pulling from the registries goes down.

If anyone else is interested in trying this fix quickly, I have a container built on https://registry.hub.docker.com/u/dsw88/registry/. The tag is 0.9.1-parallelkey-fix. I built the container from master, which appears safe at this point since there haven't been any major code changes since the 0.9.1 stable release on Jan. 8: https://github.com/docker/docker-registry/commits/master

**Comment by dsw88** [comment]
Ok it looks like I'm still seeing the EOF errors after applying the parallel key fix. I don't know yet whether their occurrence has been reduced, since I'll need to wait a few days to have enough real-world data from deploys.

But regardless, it appears that parallel key isn't the ultimate fix for this issue. Any other suggestions? Do you think it would be good to set up a Redis LRU cache? I'm wondering if having that cache would decrease the number of errors since it will need to make fewer round-trips to S3.

**Comment by dmp42** [comment]
I would definitely recommend using the Redis LRU cache.
I would also advise to delegate actual bits delivery to either S3 or a Cloudfront view of it (https://github.com/docker/docker-registry/blob/master/ADVANCED.md#s3-storage-with-cloudfront)

**Comment by dsw88** [comment]
Ok so I'm now using the LRU cache and doing S3 storage redirect. We continue to get EOF errors, but we'll see if this at least cuts it down.

I'm still concerned about the underlying issue here, however, as adding a cache is at best masking the problem. I'll try to do some debugging in the registry to find out what's causing this error, but I'm not super familiar with the codebase or technology stack so it'll be slow going.

One of my problems is I can't see any errors in the registry logs when this problem occurs. @dmp42 do you have any suggestions about how I could go about getting enough information about the error to start debugging? The Docker client isn't much help when pulling images because it just says "unexpected EOF".

**Comment by dsw88** [comment]
It appears that the small files like /ancestry and others are still failing periodically for us:
```
$ docker pull <host_name>/<image_name>:238   
Pulling repository <host_name>/<image_name>                      
2015/03/18 20:44:16 Error pulling image (<tag_name>) from <host_name>/<image_name>, 
Get http://<host_name>/v1/images/8a39dc87bd3e270444da2b7316ffcc8f7c2e65f5d91e5a3c3d2bcf17b905a7f6/ancestry: EOF                                                                                  
```

When I look in the registry logs, it shows that it got that request and even returned a 200, so presumably it thought it returned the image layer correctly:
```
[18/Mar/2015:20:44:16 +0000] "GET /v1/images/8a39dc87bd3e270444da2b7316ffcc8f7c2e65f5d91e5a3c3d2bcf17b905a7f6/ancestry HTTP/1.1" 200 3196 "-" "docker/1.1.2 go/go1.2.1 git-commit/d84a070 kernel/3.14.0-0.bpo.2-amd64 os/linux arch/amd64"
```

So are the threads in the webapp dying or timing out while it's streaming the response or something?

**Comment by dmp42** [comment]
@dsw88 I know think you are not talking about the same issue that was initially described here (the recommended workarounds were/are here to address registry side EOF/issues communicating with S3).
Your problem is more likely on the client side pipeline.

Do you use an http proxy? or a reverse-proxy in front of your registry? (nginx, HAproxy)
Do you use boot2docker?

Also, you are running a quite old version of docker (1.1.2).

I would strongly suggest upgrading if you can...

**Comment by dsw88** [comment]
@dmp42 Sorry about that, I'll open a new issue related to the EOF issues we're seeing even though we've already implemented the S3 storage redirect. I'll post there about the details of my setup.

**Comment by trinitronx** [comment]
I'm seeing errors similar to the ones mentioned in [this comment](https://github.com/benoitc/gunicorn/issues/818#issuecomment-49008067):

```
2015-03-27 20:35:14 [685] [ERROR] Error handling request
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 108, in handle_request
   resp.write(item)
 File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 344, in write
   util.write(self.sock, arg, self.chunked)
 File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 301, in write
   sock.sendall(data)
 File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
   data_sent += self.send(_get_memory(data, data_sent), flags)
 File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 435, in send
   return sock.send(data, flags)
error: [Errno 32] Broken pipe
```

I am running docker-registry (`registry:latest   Image ID: e33e81d7024c`, `"Created": "2015-03-20T22:14:39.683558078Z"`) behind jwilder/nginx-proxy (`trinitronx/nginx-proxy:latest              Image ID: 95cc04d9d18e`, `"Created": "2014-12-18T23:08:25.909249961Z"`).   My nginx-proxy container is simply based off of jwilder/nginx-proxy except I added `client_max_body_size 0;` to the `server {` block to avoid silent `docker push` failures on large image pushes.

However, the only reason that I'm running the `nginx-proxy` is to handle SSL, and when I run `docker-registry` with `storage_redirect: true` it causes SSL validation errors because docker daemon can't validate the SSL cert when it gets `302` redirected to `*.amazonaws.net`

**Comment by trinitronx** [comment]
I've tracked my SSL issue down to [this problem with S3 bucket names][1].  This seems to have solved the issue with using `-e STORAGE_REDIRECT=true`, and allows HTTPS access direct to S3.

To fix my issue I had to:

1. Copy S3 bucket to new name without dots `.` or underscores `_`  <br/>`./bin/aws s3 sync  s3://registry.example.com s3://registry-bucket-name-without-dots-and-underscores`
2. Set `-e AWS_BUCKET=registry-bucket-name-without-dots-and-underscores`
3. Restarted `docker-registry` container

Now I no longer see the `error: [Errno 32] Broken pipe` or this error:

```
Error pulling image (version_676) from registry.example.com:1234/example/web_container, Server error: Status 0 wh
ile fetching image layer (235056cffc249f5f3bfa5ba4425231ab2cf813876a43e1bc05737910c41c53f2)
[2a81fb14] -job pull(registry.example.com:1234/example/web_container, version_123) = ERR (1)
```

[1]: http://stackoverflow.com/q/18340551

**Comment by trinitronx** [comment]
Correction.... I still get the `Broken pipe` error for requests that the `docker-registry` is not giving a `302

**Comment by trinitronx** [comment]
Just noticed in my previous logs that the docker daemon (the client accessing docker-registry to pull images) has the timestamp of the error to be: `2015/04/09 17:32:18`

I searched for that time in the logs (`17:32:18`) and couldn't find it, so I noticed that clocks on the (docker daemon host) and (`docker-registry` / `nginx-proxy`) host are set in different time zones.

I checked the `date` on the host running docker daemon and the one running the `nginx-proxy` and `docker-registry` containers to determine if there was a time offset and prove to myself that the clocks were synchronized correctly via NTP.  This will help us in lining up the timing of events.  Here are the results:

```
"docker daemon" host: Thu Apr  9 18:57:44 MDT 2015 = 2015-04-09 18:57:44 -0600 = 2015-04-10 00:57:44 UTC
docker-registry host: Fri Apr 10 00:57:44 UTC 2015 = 2015-04-10 00:57:44 UTC
```

So both hosts are synchronized to correct time, but are just in different time zones.  One is UTC, one is UTC-6 hours.  So we just add 6 hours to the docker daemon host time:  

```
'2015/04/09 17:32:18' => 2015-04-09 17:32:18 -0600 => 2015-04-09 23:32:18 UTC
```

Searching `nginx-proxy` logs for `23:32:18` gives 2 matches:

```
nginx.1    | 12.34.56.78 - - [09/Apr/2015:23:32:18 +0000] "GET /v1/images/2b0c589adcfd8d65c643179f0cb243e9ba93c5ae80c0c1b4a5a194d6a868e659/ancestry HTTP/1.1" 499 0 "-" "docker/1.3.3 go/go1.3.3 git-commit/d344625 kernel/2.6.32-431.el6.x86_64 os/linux arch/amd64" "-"
nginx.1    | registry.example.com 12.34.56.78 - - [09/Apr/2015:23:32:18 +0000] "GET /v1/images/2b0c589adcfd8d65c643179f0cb243e9ba93c5ae80c0c1b4a5a194d6a868e659/ancestry HTTP/1.1" 499 0 "-" "docker/1.3.3 go/go1.3.3 git-commit/d344625 kernel/2.6.32-431.el6.x86_64 os/linux arch/amd64"
```

Searching `docker-registry` logs for `23:32:18` gives *NO* matches!  Something fishy is going on...

So nginx is seeing the request from docker daemon for `GET /v1/images/2b0c589adcfd8d65c643179f0cb243e9ba93c5ae80c0c1b4a5a194d6a868e659/ancestry`.  It then logs HTTP code `499`.

And nginx shows [HTTP Code `499`](http://httpstatus.es/499)

Making the assumption that Nginx is telling us the truth:  the client closed it's connection before it could hear a response.  Here is what I think is happening:

1. `sudo docker pull registry.example.com:443/example/web_container:version_123` is run
2. `2015-04-09 23:32:18 UTC`:  docker daemon performs the request against `nginx-proxy`: `GET /v1/images/2b0c589adcfd8d65c643179f0cb243e9ba93c5ae80c0c1b4a5a194d6a868e659/ancestry`
3. docker daemon disconnects quickly
4. `2015-04-09 23:32:18 UTC`:  `nginx-proxy` logs the request & HTTP Status `499`
5. `2015-04-09 23:36:38 UTC`: `docker-registry` logs the `Broken pipe` error:

```
[2015-04-09 23:36:35 +0000] [65] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 108, in handle_request
    resp.write(item)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 344, in write
    util.write(self.sock, arg, self.chunked)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 301, in write
    sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
```

The `docker-registry` then throws the `Broken pipe` error at: `2015-04-09 23:36:38 UTC`.

So from the time that the docker daemon makes the request `2015-04-09 23:32:18 UTC` to the time that the error occurs at `2015-04-09 23:36:38 UTC`, this much time has elapsed:

```
0:04:20   (h:m:s)
260.00    total seconds
4.33      total minutes
0.07      total hours
```

Given the symptoms, and proposed chain of events... This could potentially related to benoitc/gunicorn#414


The `docker-registry` container is running:

```
root@docker-registry:/# gunicorn -v
gunicorn (version 19.1.1)
```

And it has these python packages installed:

```
root@docker-registry:/# pip list
argparse (1.2.1)
backports.lzma (0.0.3)
blinker (1.3)
boto (2.34.0)
bugsnag (2.0.2)
chardet (2.0.1)
colorama (0.2.5)
docker-registry (0.9.1)
docker-registry-core (2.0.3)
Flask (0.10.1)
Flask-Cors (1.10.3)
gevent (1.0.1)
greenlet (0.4.5)
gunicorn (19.1.1)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.3)
M2Crypto (0.22.3)
MarkupSafe (0.23)
newrelic (2.22.1.20)
pip (1.5.4)
PyYAML (3.11)
redis (2.10.3)
requests (2.3.0)
setuptools (5.8)
simplejson (3.6.2)
six (1.5.2)
SQLAlchemy (0.9.4)
urllib3 (1.7.1)
WebOb (1.4)
Werkzeug (0.10.1)
wsgiref (0.1.2)
```

**Comment by trinitronx** [comment]
I'm able to reproduce this error easily by running the `docker-registry-ui` container:

```
boot2docker init
boot2docker up
eval $(boot2docker shellinit bash)

# start 
docker run -d \
  -p 80:80 \
  -p 443:443 \
  -v /var/run/docker.sock:/tmp/docker.sock \
  -v /etc/docker/certs.d/:/etc/nginx/certs \
  --name=nginx-proxy \
  -t trinitronx/nginx-proxy

# start docker-registry-ui
docker run -d \
          -p 8080:8080 \
          -e REG1=https://registry.example.com:443/v1/ \
          --name=docker-registry-ui
          atcol/docker-registry-ui
```

Watch the logs by opening 3 terminals:

```
# Terminal 1
docker logs -f nginx-proxy
# Terminal 2
docker logs -f docker-registry
# Terminal 3
docker logs -f docker-registry-ui
```

I then simply access the "Images" page through the [`docker-registry-ui`](https://github.com/atc-/docker-registry-ui) Web UI via URL: `http://ip-of-boot2docker-box:8080/repository/index`.

Here are are all 3 [anonymized logs](https://gist.github.com/trinitronx/ab61cbc9bddce82037c6)

The other way to reproduce it, although not as easy perhaps, is to do **lots** of `docker pull` commands in succession for different images / tagged containers.

**Comment by trinitronx** [comment]
Got another instance of this bug, with different request for `/repositories/*/*/images` endpoint.  However, same `504 Gateway Timeout`, similar stacktrace & error `Broken Pipe` from `gevent`.

[Here are the logs](https://gist.github.com/trinitronx/15078746b31d310c1a35).  There are a couple requests in the logs.. the first couple are from the initial `docker pull` that failed.  The next couple are from 2 manual cURL requests I performed.  One reproduced the error, the other didn't.  This bug is odd in that it only occurs sometimes, but not always.  Usually a second retry is successful.  Like I mentioned before, the easiest way to reproduce it is to run the registry UI and just hit some pages to search around for images.

This bug looks a lot like gevent/gevent#445

**Comment by trinitronx** [comment]
There are other similar bugs on [`gevent`'s GitHub issue tracker](https://github.com/gevent/gevent/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Broken+pipe)

The ones that most notably seem related:

 - [gevent/gevent#377](https://github.com/gevent/gevent/pull/377)
 - [gevent/gevent#136](https://github.com/gevent/gevent/issues/136)

**Comment by trinitronx** [comment]
After enabling the `SEARCH_BACKEND` and `GUNICORN_OPTS='[--preload]'` options to the docker registry, we ran into [stability issues (docker/docker-registry#540)](https://github.com/docker/docker-registry/issues/540).

After disabling both of these options, these stability issues went away and errors became much less frequent (although seemed to be present but still sometimes occurred).

Didn't have enough time to investigate further, but turning off search and disabling the `--preload` option did alleviate the issue.

Since this project is deprecated, hopefully this helps anyone still stuck on Registry V1.
